name: jax11
channels:
  - conda-forge
  - defaults
dependencies:
  - blas=2.120
  - blas-devel=3.9.0
  - bzip2=1.0.8
  - ca-certificates=2023.11.17
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=16.0.6
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libopenblas=0.3.25
  - llvm-openmp=17.0.6
  - ml_dtypes=0.2.0
  - ncurses=6.4
  - openblas=0.3.25
  - openssl=3.2.0
  - opt_einsum=3.3.0
  - pip=23.3.1
  - python=3.11.5
  - readline=8.2
  - scipy=1.11.4
  - setuptools=68.0.0
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2023c
  - wheel=0.41.2
  - xz=5.4.5
  - zlib=1.2.13
  - pip:
    - absl-py==2.0.0
    - astunparse==1.6.3
    - attrs==23.1.0
    - blackjax==1.0.0
    - cachetools==5.3.2
    - certifi==2023.11.17
    - charset-normalizer==3.3.2
    - chex==0.1.85
    - contourpy==1.2.0
    - cycler==0.12.1
    - diffrax==0.4.1
    - equinox==0.11.2
    - fastprogress==1.0.3
    - filelock==3.13.1
    - flatbuffers==23.5.26
    - fonttools==4.46.0
    - fsspec==2023.12.2
    - gast==0.5.4
    - google-auth==2.25.2
    - google-auth-oauthlib==1.2.0
    - google-pasta==0.2.0
    - grpcio==1.60.0
    - gviz-api==1.10.0
    - h5py==3.10.0
    - idna==3.6
    - iniconfig==2.0.0
    - jax==0.4.21
    - jax-tqdm==0.1.2
    - jaxlib==0.4.21
    - jaxopt==0.8.2
    - jaxtyping==0.2.24
    - jinja2==3.1.2
    - keras==2.15.0
    - kiwisolver==1.4.5
    - libclang==16.0.6
    - lineax==0.0.3
    - markdown==3.5.1
    - markupsafe==2.1.3
    - matplotlib==3.8.2
    - mpmath==1.3.0
    - multipledispatch==1.0.0
    - networkx==3.2.1
    - numpy==1.24.4
    - numpyro==0.13.2
    - oauthlib==3.2.2
    - optax==0.1.7
    - ott-jax==0.4.4
    - packaging==23.2
    - pillow==10.1.0
    - pluggy==1.4.0
    - protobuf==4.23.4
    - pyasn1==0.5.1
    - pyasn1-modules==0.3.0
    - pygments==2.17.2
    - pyparsing==3.1.1
    - pytest==7.4.4
    - python-dateutil==2.8.2
    - requests==2.31.0
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - six==1.16.0
    - sympy==1.12
    - tensorboard==2.15.1
    - tensorboard-data-server==0.7.2
    - tensorboard-plugin-profile==2.15.0
    - tensorflow==2.15.0
    - tensorflow-estimator==2.15.0
    - tensorflow-io-gcs-filesystem==0.34.0
    - tensorflow-macos==2.15.0
    - termcolor==2.4.0
    - toolz==0.12.0
    - torch==2.1.1
    - tqdm==4.66.1
    - typeguard==2.13.3
    - typing-extensions==4.9.0
    - urllib3==2.1.0
    - werkzeug==3.0.1
    - wmctrl==0.5
    - wrapt==1.14.1
